name: raffle_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5
  flutter_bloc: ^8.1.6
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  flutter_fortune_wheel: ^1.3.2
  connectivity_plus: ^6.1.0
  flutter_easyloading: ^3.0.5
  confetti: ^0.8.0
  lottie: ^3.1.3
  flutter_slot_machine: ^0.0.1
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - lib/utils/assets/images/
    - assets/lottie/
