// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiu119r27SmZWcYD41n6qAJiyJOZ23M88',
    appId: '1:143060704309:web:5a942f5a7ee44bb14fe57c',
    messagingSenderId: '143060704309',
    projectId: 'bet-wheel-app',
    authDomain: 'bet-wheel-app.firebaseapp.com',
    storageBucket: 'bet-wheel-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg1TujeAVrjdGnhhfBnTlbsWHxfkumQzA',
    appId: '1:143060704309:android:7ee83de5af676d5f4fe57c',
    messagingSenderId: '143060704309',
    projectId: 'bet-wheel-app',
    storageBucket: 'bet-wheel-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-CXXQMQaM-EdvEAMfwlwUB404Mc2lrdY',
    appId: '1:143060704309:ios:a362e32eedfd57d04fe57c',
    messagingSenderId: '143060704309',
    projectId: 'bet-wheel-app',
    storageBucket: 'bet-wheel-app.firebasestorage.app',
    iosBundleId: 'com.example.raffleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-CXXQMQaM-EdvEAMfwlwUB404Mc2lrdY',
    appId: '1:143060704309:ios:a362e32eedfd57d04fe57c',
    messagingSenderId: '143060704309',
    projectId: 'bet-wheel-app',
    storageBucket: 'bet-wheel-app.firebasestorage.app',
    iosBundleId: 'com.example.raffleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiu119r27SmZWcYD41n6qAJiyJOZ23M88',
    appId: '1:143060704309:web:5b8e881997ffc3574fe57c',
    messagingSenderId: '143060704309',
    projectId: 'bet-wheel-app',
    authDomain: 'bet-wheel-app.firebaseapp.com',
    storageBucket: 'bet-wheel-app.firebasestorage.app',
  );
}
